name: Terraform Module Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TF_CLOUD_HOSTNAME: ${{vars.TF_CLOUD_HOSTNAME}}
      TF_CLOUD_ORGANIZATION: ${{vars.TF_CLOUD_ORGANIZATION}}
      TF_WORKSPACE: ${{vars.TF_WORKSPACE}}
      TF_TOKEN: ${{secrets.TF_TOKEN}}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: Terraform Version
        run: terraform -v

      - name: Initialize Terraform
        run: terraform init
      
      - name: Validate Terraform
        run: terraform validate

      - name: Plan changes
        run: terraform plan
      
      - name: Apply changes
        run: terraform apply -auto-approve
      
      - name: Run additional tests
        run: |
          cat index.html

      - name: Destroy
        run: terraform destroy -auto-approve